"""create_subscriptions_and_anomalies

Revision ID: 3c85f5c111e0
Revises: f3a516ab1779
Create Date: 2026-06-06 23:24:39.022197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM



# revision identifiers, used by Alembic.
revision: str = '3c85f5c111e0'
down_revision: Union[str, Sequence[str], None] = 'f3a516ab1779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cadence_days', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_subscriptions_user_id'), 'detected_subscriptions', ['user_id'], unique=False)
    op.create_table('flagged_anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('category', ENUM('groceries', 'restaurants', 'transport', 'fuel', 'utilities', 'rent', 'health', 'entertainment', 'shopping', 'subscriptions', 'travel', 'education', 'income', 'transfer', 'uncategorized', name='transaction_category', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flagged_anomalies_transaction_id'), 'flagged_anomalies', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_flagged_anomalies_user_id'), 'flagged_anomalies', ['user_id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_monthly_category_rollups_category'), 'monthly_category_rollups', ['category'], unique=False)
    op.create_index(op.f('ix_monthly_category_rollups_month'), 'monthly_category_rollups', ['month'], unique=False)
    op.create_index(op.f('ix_monthly_category_rollups_user_id'), 'monthly_category_rollups', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.drop_index(op.f('idx_users_clerk_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.create_index(op.f('idx_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_index(op.f('ix_monthly_category_rollups_user_id'), table_name='monthly_category_rollups')
    op.drop_index(op.f('ix_monthly_category_rollups_month'), table_name='monthly_category_rollups')
    op.drop_index(op.f('ix_monthly_category_rollups_category'), table_name='monthly_category_rollups')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_flagged_anomalies_user_id'), table_name='flagged_anomalies')
    op.drop_index(op.f('ix_flagged_anomalies_transaction_id'), table_name='flagged_anomalies')
    op.drop_table('flagged_anomalies')
    op.drop_index(op.f('ix_detected_subscriptions_user_id'), table_name='detected_subscriptions')
    op.drop_table('detected_subscriptions')
    # ### end Alembic commands ###
